### ISSUE TITLE
should it work with LS-WVL ?

### ISSUE THREAD

**Issue by janpxr** [1000001101000/acp-commander#8]
Name: LS-WVL91B
Firmware version: 1.75

The "NAS Navigator2" finds the device.
Windows Firewall turned off.

`java -jar acp_commander.jar -f
Welcome to ACP Commander v0.6 (2021), the tool for Buffalo stock firmware control!

+----------+-----+----+-------------------+------------+----------+
| Hostname | MAC | IP | Product ID String | Product ID | Firmware |
+----------+-----+----+-------------------+------------+----------+

Found 0 devices.`

Ideas?

**Comment by 1000001101000** [comment]
Good to hear from you!

As far as I know it should, I'm reasonably sure I've tried it with a device of that generation running that same firmware at some point. 

I don't know that much about NasNavigator, I'm not sure if the ACP protocol is the only thing it uses to find devices for not. Could you try downloading the firmware updater for this device and see if LSUpdater is also able to find it?

**Comment by janpxr** [comment]
thanks for quick feeback.

yes, LSUpdater is able to find the device.

**Comment by 1000001101000** [comment]
Without knowing any details, I would guess that your system has multiple network adapters and LSUpdater is doing a better job of picking the correct one than acp_commader. 

Try using "-b" with the ip address of your computer
```
-b localip.. bind socket to local address. Use if acp_commander
                can not find your device (might use wrong adapter).
```
If that doesn't work post some information about the system you're running acp_commander on and we can look at next steps.

**Comment by janpxr** [comment]
i have the LS-WVL91B now wired directly to PC.

`
java -jar acp_commander.jar -f
Welcome to ACP Commander v0.6 (2021), the tool for Buffalo stock firmware control!

+----------+-----+----+-------------------+------------+----------+
| Hostname | MAC | IP | Product ID String | Product ID | Firmware |
+----------+-----+----+-------------------+------------+----------+

Found 0 devices.
`

The LSUpdater and Buffalo NAS Navigator2 both find the device.

What should the ip address of the PC be in this case then to be used with the -b flag? How should the command look like?
`
java -jar acp_commander.jar -t 127.0.0.1 -f
Welcome to ACP Commander v0.6 (2021), the tool for Buffalo stock firmware control!

+----------+-----+----+-------------------+------------+----------+
| Hostname | MAC | IP | Product ID String | Product ID | Firmware |
+----------+-----+----+-------------------+------------+----------+

Found 0 devices.
`

**Comment by 1000001101000** [comment]
What OS is your PC?

Since LSUpdater worked I don’t think connecting directly is needed. It’s a good idea, but may complicate things.

The ip address you want is the address the device would see on the network. Usually something like 192.168.x.x
